services:
  - type: worker
    name: senzir
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python senzir.py
    envVars:
          - key: APP_ID
            sync: false
          - key: API_HASH
            sync: false
          - key: BOT_TOKEN
            sync: false
          - key: ENV
            value: ANYTHING
          - key: STRING_SESSION
            sync: false